container_detection:
    model_spec_name: GLS_container_detection
    input_shape: [640, 640, 3]
    input_name: images
    input_type: FP32
    max_batch_size: 1
    output_name: output0
    iou_threshold: 0.5
    conf_threshold: 0.3
    request_timeout: 60.0



container_info_detection:
    model_spec_name: GLS_container_info_detection
    input_shape: [640, 640, 3]
    input_name: images
    input_type: FP32
    max_batch_size: 1
    output_name: output0
    iou_threshold: 0.5
    conf_threshold: 0.3
    request_timeout: 60.0


container_defect_detection:
    model_spec_name: GLS_container_defect_detection
    input_shape: [640, 640, 3]
    input_name: images
    input_type: FP32
    max_batch_size: 1
    output_name: output0
    iou_threshold: 0.5
    conf_threshold: 0.3
    request_timeout: 60.0


license_plate_ocr:
  model_spec_name: general_lp_ocr
  input_shape: [70, 140, 1]
  input_name: input
  input_type: UINT8
  max_batch_size: 1
  output_name: concatenate
  request_timeout: 60.0

ppocrv4_rec:
    model_spec_name: ppocrv4_rec
    input_shape: [48, 320, 3]
    input_name: x
    input_type: FP32
    max_batch_size: 8
    output_name: softmax_2.tmp_0
    request_timeout: 60.0

vietnamese_lp_ocr:
    model_spec_name: vietnamese_lp_ocr
    input_name: input
    input_shape: [48, 112, 3]
    input_type: FP32
    max_sequence_length: 10
    charset: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    max_batch_size: 4
    output_name: output
    request_timeout: 60.0
